app/image/__init__.py
from flask import Blueprint

image = Blueprint('image', __name__)
from . import views

app/image/views.py
import sys
from flask import flash, render_template, request, send_file, redirect, url_for
from base64 import b64encode
from flask_login import current_user, login_required

from . import image
from ..models import Image, MediaType

IMAGE_FORMAT=["jpg", "png"]
VIDEO_FORMAT="mp4"

@image.route("/image/view/<string:imageid>")
@login_required
def image_view(imageid):
    img = Image.objects.get_or_404(id=imageid, user=current_user.id)
    media = b64encode(img.data).decode("utf-8")
    if img.mtype == MediaType.IMAGE:
        return render_template('image/view-image.html', image=media)
    if img.mtype == MediaType.VIDEO:
        return render_template('image/view-video.html', video=media)
    flash('Bad media format.', 'danger')
    return redirect(url_for('image.images_list'))
    #return send_file(io.BytesIO(img.data), attachment_filename='img.filename', mimetype='image/jpg')


@image.route('/image/add', methods = ['post', 'get'])
@login_required
def image_add():
    if request.method == 'POST':
        file = request.files['image']
        mtype = None
        if (file.filename.endswith(VIDEO_FORMAT)):
            mtype = MediaType.VIDEO
        else:
            for ext in IMAGE_FORMAT:
                if (file.filename.endswith(ext)):
                    mtype = MediaType.IMAGE
            if mtype is None:
                flash('Bad media format.', 'danger')
                return redirect(url_for('image.images_list'))
        try:
            img = Image(user=current_user.id, name=file.filename, data=file.read(), mtype=mtype)
            img.create()
            flash('image recorded, id={}'.format(str(img.id)), 'success')
        except Exception as e:
            flash('error to save Image', 'danger')
        return redirect(url_for('image.images_list'))
    return render_template('image/add-image.html')


@image.route('/image-capture', methods = ['get'])
@login_required
def image_capture():
    return render_template('image/capture-image.html', title='capture an image')


@image.route('/images', methods = ['get'])
@login_required
def images_list():
    images = Image.objects(user=current_user.id)
    return render_template('image/list-images.html', images=images, media_types_list=MediaType, title='Liste des images')



@image.route('/image/delete/<string:imageid>', methods = ['get', 'post'])
@login_required
def image_delete(imageid):
    img = Image.objects.get_or_404(id=imageid, user=current_user.id)
    img.delete()
    flash("Image {} Deleted".format(image.name), 'success')
    return redirect(url_for('image.images_list'))
 

app/templates/image/add-image.html
{% extends 'layout/base.html' %}

{% block content %}

      <div class="row">
         <div class="col">
           <div class="mb-3 mt-3">
   
             <h2 class="mb-3" style="font-weight: 300">Upload image</h2>
   
             <form action="{{ url_for('image.image_add') }}" method="POST" enctype="multipart/form-data" class="mb-3">
               <div class="form-group mb-3">
                 <div class="custom-file">
                   <input type="file" class="custom-file-input" name="image">
                   <label id="file_input_label" class="custom-file-label" for="image">Select file</label>
                   <small class="text-muted">Images should have jpg or png format</small>
                 </div>
               </div>
   
               <button type="submit" class="btn btn-primary">Upload</button>
             </form>
           </div>
         </div>
       </div> 
{% endblock %}

app/templates/image/capture-image.html
{% extends 'layout/base.html' %}

{% block content %}
<p>Record pictures and video.</p>
<p><button id="record" disabled>Record</button> <button id="stop" disabled>Stop</button> <button id="snap">Snap</button></p>
<div class="row"></div>
    <figure>
        <video id="live" width="640" height=480></video><br />
        <caption>live preview</caption>
    </figure>
    <figure>
        <video id="recording" controls width="1280" height=720></video><br />
        <caption>recorded clip</caption>
    </figure>
    <figure>
        <canvas id="picture" controls width=1280 height=720></canvas><br />
        <caption>picture</caption>
    </figure>
  </div>
{% endblock %}

{% block script %} 
<script src="{{ url_for('static',filename='js/capture.js') }}"></script>
{% endblock %}

app/templates/image/list-images.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container-fluid"> 
    <table id="mytable" class="table tablesorter mb-5">
      <caption>
        Images list
        <a href="{{ url_for('image.image_add') }}"" class="btn btn-sm btn-secondary ml-3">Add image</a>
      </caption>
      <thead class="cf">
        <tr>
          <th scope="col" class="header">ID</th>
          <th scope="col" class="header">Name</th>
          <th scope="col" class="header">Type</th>
          <th scope="col" class="header">Size</th>
          <th scope="col" class="header">Recorded At</th>
          <th scope="col" class="header">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for image in images%} 
        <tr> 
          <td class="align-middle">{{ image.id }}</td>
          <td class="align-middle">{{ image.name|title }}</td>
          <td class="align-middle">{{ media_types_list(image.mtype).name.capitalize() }} </td>
          <td class="align-middle">{{ image.size }}</td>
          <td class="align-middle">{{ image.recorded_at.strftime('%y/%m/%d %H:%M') }}</td>
          <td class="align-middle">
            <a href="{{ url_for('image.image_view', imageid=image.id) }}" class="btn btn-sm btn-primary">View</a>
            <a href="{{ url_for('image.image_delete', imageid=image.id) }}" class="btn btn-sm btn-danger">Delete</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

{% endblock %}

app/templates/image/view-image.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container mt-3">
    <div class="row">
      <div class="col">
        <img src="data:;base64,{{ image }}" class="img-fluid" alt="Responsive image"/>
      </div>
    </div>
  </div>
  {% endblock %}

app/templates/image/view-video.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container mt-3">
    <div class="row">
      <div class="col">
        <video  controls>
          <source src="data:;base64,{{ video }}" type="video/mp4"/>
        </video>
      </div>
    </div>
  </div>
  {% endblock %}