app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, PasswordField, BooleanField
from wtforms.fields import SelectField
from wtforms.validators import DataRequired, Length, Email

class UserEditForm(FlaskForm):
    id        = StringField   (u'id')
    username  = StringField   (u'username' , validators=[validators.Length(min=4, max=25, message='Field must be between 4 and 25 characters long.')])
    email     = StringField   (u'email'    , validators=[Email(message='Not a valid email address.')])
    firstname = StringField   (u'firstname', validators=[validators.Length(min=2, message='Field must be at least 2 character long.')])
    lastname  = StringField   (u'lastname' , validators=[validators.Length(min=2, message='Field must be at least 2 character long.')])
    role      = SelectField   (u'role'     , validate_choice=False)
    active    = BooleanField  (u'active')
    submit    = SubmitField   (u'Submit')
    back      = SubmitField   (u'Back')


class UserForm(FlaskForm):
    username  = StringField   (u'username' , validators=[validators.Length(min=4, max=25, message='Field must be between 4 and 25 characters long.')])
    email     = StringField   (u'email'    , validators=[Email(message='Invalid email address.')])
    firstname = StringField   (u'firstname', validators=[validators.Length(min=2, message='Field must be at least 2 character long.')])
    lastname  = StringField   (u'lastname' , validators=[validators.Length(min=2, message='Field must be at least 2 character long.')])
    password  = PasswordField (u'password' , validators=[Length(min=4, message='Field must be at least 4 character long.')])
    #role = SelectField   (u'role', choices=[(member.value, name) for name, member in UserRole.__members__.items()], validators=[InputRequired()])
    #role = SelectField   (u'role', choices=[(1,"Guest"),(2,"User"), (3,"Admin")]) 
    role      = SelectField   (u'role'     , validate_choice=False)
    submit    = SubmitField   (u'Submit')
    back      = SubmitField   (u'Back')

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)
from . import views

app/user/views.py
from flask import render_template, url_for, request, redirect, flash
from flask_login import login_required, current_user

from . import user
from ..models import User, UserRole
from .forms import UserForm, UserEditForm
from ..utils import admin_required, owner_or_admin_required

@user.route('/user/add', methods=['get', 'post'])
@admin_required
def user_add():
    form = UserForm()
    if request.method == 'POST':
        if form.back.data:
            return redirect(url_for('user.users_list'))
            
        if form.validate_on_submit():
            try:
                user = User(username=form.username.data, 
                            firstname=form.firstname.data, 
                            lastname=form.lastname.data , 
                            email=form.email.data, 
                            role=int(form.role.data),
                            password=form.password.data)
                user.create()
                flash('user {} created'.format(user.username), 'success')
                return redirect(url_for('user.users_list'))
            except Exception as e:
                flash('user not created, error:' + str(e), 'danger')

    return render_template('user/add-user.html', form=form, roles_list=UserRole, title='add user')

 
  
@user.route('/user/delete/<string:userid>', methods = ['get', 'post'])
@admin_required
def user_delete(userid):
    user = User.objects.get_or_404(id=userid)
    if str(current_user.id) == userid:
        flash('unauthorized operation', 'danger')
    else:
        user.delete()
        flash("User {} Deleted".format(user.username), 'success')
    return redirect(url_for('user.users_list'))
 
 
@user.route('/user/edit/<string:userid>', methods = ['get', 'post'])
@owner_or_admin_required
def user_edit(userid):
    user = User.objects.get_or_404(id=userid)
    form = UserEditForm(obj=user)
    owner = userid == str(current_user.id)
    admin = current_user.is_admin()

    if request.method == 'POST':
        if form.back.data:
            return redirect(url_for('user.users_list'))
            
        if form.validate_on_submit():
            try:
                if owner:
                    user.username=form.username.data
                    user.firstname=form.firstname.data
                    user.lastname=form.lastname.data
                    user.email=form.email.data
                if admin:
                    user.role=int(form.role.data)
                    user.active=form.active.data
                user.save()
                flash('user {} updated'.format(user.username), 'success')
                return redirect(url_for('user.users_list'))
            except Exception as e:
                msg = 'Error, your account is not register:' + str(e)
                flash(msg, 'danger')
 
    return render_template('user/edit-user.html', form=form, roles_list=UserRole, owner=owner, admin=admin, title='edit user')
 

@user.route('/users', methods = ['get'])
@login_required
def users_list():
    return render_template('user/list-users.html', users=User.objects(), roles_list=UserRole, admin=current_user.is_admin(), title='Liste des utilisateurs')

app/templates/user/add-user.html
{% extends 'layout/base.html' %}

{% block content %}

<form action="{{ url_for('user.user_add') }}" method="post">
    <div class="user">
        <div class="user-screen">
            <div class="user-title">
                <h1>Add User</h1>
            </div>
            <div class="user-form">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username.label(class="form-label is-required") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <ul class="errors invalid-feedback">
                            {% for error in form.username.errors %}
                                {{ error }}
                            {% endfor %}
                        </ul>
                    {% else %}
                        {{ form.username(class="form-control" ) }}
                    {% endif %}

                <div class="form-group">
                    {{ form.firstname.label(class="form-label is-required") }}
                    {% if form.firstname.errors %}
                        {{ form.firstname(class="form-control is-invalid") }}
                        <ul class="errors invalid-feedback">
                            {% for error in form.firstname.errors %}
                                {{ error }}
                            {% endfor %}
                        </ul>
                    {% else %}
                        {{ form.firstname(class="form-control" ) }}
                    {% endif %}

                <div class="form-group">
                    {{ form.lastname.label(class="form-label is-required") }}
                    {% if form.lastname.errors %}
                    {{ form.lastname(class="form-control is-invalid") }}
                    <ul class="errors invalid-feedback">
                        {% for error in form.lastname.errors %}
                            {{ error }}
                        {% endfor %}
                    </ul>
                {% else %}
                    {{ form.lastname(class="form-control" ) }}
                {% endif %}
                
                <div class="form-group">
                    {{ form.email.label(class="form-label is-required") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <ul class="errors invalid-feedback">
                            {% for error in form.email.errors %}
                                {{ error }}
                            {% endfor %}
                        </ul>
                    {% else %}
                        {{ form.email(class="form-control" ) }}
                    {% endif %}

                <div class="form-group">
                    {{ form.role.label(class="form-label") }}
                        <select name="role" class="custom-select">
                        {% for role in roles_list %}
                            <option value="{{ role.value }}"" selected>{{ role.name.capitalize() }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-label is-required") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <ul class="errors invalid-feedback">
                            {% for error in form.password.errors %}
                                {{ error }}
                            {% endfor %}
                        </ul>
                    {% else %}
                        {{ form.password(class="form-control" ) }}
                    {% endif %}

                <div class="btn-group">
                    {{ form.back(class="btn btn-secondary mr-3") }}
                    {{ form.submit(class="btn btn-primary mr-3") }}
                 </div>

            </div>
        </div>
    </div>
</form>
{% endblock %}

app/templates/user/edit-user.html
{% extends 'layout/base.html' %}

{% block content %}

<form action="{{ url_for('user.user_edit', userid=form.id.data) }}" method="post">
    <div class="user">
        <div class="user-screen">
            <div class="user-title">
                <h1>Edit User</h1>
            </div>
            <div class="user-form">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username.label(class="form-label is-required") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <ul class="errors invalid-feedback">
                            {% for error in form.username.errors %}
                                {{ error }}
                            {% endfor %}
                        </ul>
                    {% else %}
                        {% if not owner %}
                            {{ form.username(class="form-control", disabled=True) }}
                        {% else %}
                            {{ form.username(class="form-control") }}
                        {% endif %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.firstname.label(class="form-label is-required") }}
                    {% if form.firstname.errors %}
                        {{ form.firstname(class="form-control is-invalid") }}
                        <ul class="errors invalid-feedback">
                            {% for error in form.firstname.errors %}
                                {{ error }}
                            {% endfor %}
                        </ul>
                    {% else %}
                        {% if not owner %}
                            {{ form.firstname(class="form-control", disabled=True) }}
                        {% else %}
                            {{ form.firstname(class="form-control") }}
                        {% endif %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.lastname.label(class="form-label is-required") }}
                    {% if form.lastname.errors %}
                        {{ form.lastname(class="form-control is-invalid") }}
                        <ul class="errors invalid-feedback">
                            {% for error in form.lastname.errors %}
                                {{ error }}
                            {% endfor %}
                        </ul>
                    {% else %}
                        {% if not owner %}
                            {{ form.lastname(class="form-control", disabled=True) }}
                        {% else %}
                            {{ form.lastname(class="form-control") }}
                        {% endif %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-label is-required") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <ul class="errors invalid-feedback">
                        {% for error in form.email.errors %}
                            {{ error }}
                        {% endfor %}
                    </ul>
                {% else %}
                    {% if not owner %}
                        {{ form.email(class="form-control", disabled=True) }}
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                {% endif %}
               </div>

                <div class="form-group">
                    {{ form.role.label(class="form-label") }}
                    <select name="role" class="custom-select" {% if not admin %} disabled=True {% endif %}>
                    {% for r in roles_list %}
                        <option value="{{ r.value }}" {% if r.value|int == form.role.data|int %} selected {% endif %}>{{ r.name.capitalize() }}</option>
                    {% endfor %}
      
                    </select>
                </div>

                <div class="form-group">
                  <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" id="active" name="active" {% if form.active.data %} checked {% endif %} {% if not admin %} disabled=True {% endif %}>
                    {{ form.active.label(class="custom-control-label") }}
                  </div>
                </div>

                <div class="btn-group action-form">
                  {{ form.back(class="btn btn-secondary mr-3") }}
                  {{ form.submit(class="btn btn-primary mr-3") }}
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

app/templates/user/list-users.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container-fluid"> 
    <table id="mytable" class="table tablesorter mb-5">
      <caption>
        Users list
        {% if admin %}
          <a href="{{ url_for('user.user_add') }}"" class="btn btn-sm btn-secondary ml-3">Add user</a>
        {% endif %}
      </caption>
      <thead class="cf">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Username</th>
          <th scope="col">Email</th>
          <th scope="col">Role</th>
          <th scope="col">Is active</th>
          <th scope="col">Connected</th>
          <th scope="col">Created At</th>
          <th scope="col">Last login</th>
          {% if admin %}
            <th scope="col">Actions</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for user in users %} 
        <tr> 
          <td class="align-middle">{{ user.id }}</td>
          <td class="align-middle">{{ user.username|title }}</td>
          <td class="align-middle">{{ user.email }}</td>
          <td class="align-middle">{{ roles_list(user.role).name.capitalize() }} </td>
          <td class="align-middle">{{ user.active }}</td>
          <td class="align-middle">{{ user.connected }}</td>
          <td class="align-middle">{{ user.created_at.strftime('%y/%m/%d %H:%M') }}</td>
          <td class="align-middle">{{ user.last_login.strftime('%y/%m/%d %H:%M') if user.last_login }}</td>
          {% if admin %}
            <td class="align-middle">
              <a href="{{ url_for('user.user_edit', userid=user.id) }}" class="btn btn-sm btn-primary">Edit</a>
              <a href="{{ url_for('user.user_delete', userid=user.id) }}" class="btn btn-sm btn-danger">Delete</button>
            </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
</div>

{% endblock %}